// Auto-Generated by FAKE; do not edit
namespace System
open System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Akka.FSharp")>]
[<assembly: AssemblyProductAttribute("Akka.NET")>]
[<assembly: AssemblyDescriptionAttribute("Akka.NET is a port of the popular Java/Scala framework Akka to .NET")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2013-2016 Akka.NET Team")>]
[<assembly: AssemblyCompanyAttribute("Akka.NET Team")>]
[<assembly: ComVisibleAttribute(false)>]
[<assembly: CLSCompliantAttribute(true)>]
[<assembly: AssemblyVersionAttribute("1.1.2.0")>]
[<assembly: AssemblyFileVersionAttribute("1.1.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Akka.FSharp"
    let [<Literal>] AssemblyProduct = "Akka.NET"
    let [<Literal>] AssemblyDescription = "Akka.NET is a port of the popular Java/Scala framework Akka to .NET"
    let [<Literal>] AssemblyCopyright = "Copyright © 2013-2016 Akka.NET Team"
    let [<Literal>] AssemblyCompany = "Akka.NET Team"
    let [<Literal>] ComVisible = false
    let [<Literal>] CLSCompliant = true
    let [<Literal>] AssemblyVersion = "1.1.2.0"
    let [<Literal>] AssemblyFileVersion = "1.1.2.0"
